services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      ATTACHMENT_DIR: ${ATTACHMENT_DIR:-/app/attachments}
      ICLOUD_USERNAME: ${ICLOUD_USERNAME}
      ICLOUD_PASSWORD: ${ICLOUD_PASSWORD}
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      PYTHONUNBUFFERED: "1"
    working_dir: /app/
    command: >
      sh -c "
        alembic upgrade head &&
        python -m shiftbot.main
      "
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
